spring:
  application:
    name: barberconnect

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  jpa:
    hibernate:
      ddl-auto: validate

jwt:
  expiration-minutes: 60

refresh-token:
  expiration-days: 7

otp:
  expiration-minutes: 10
  max-attempts: 5